```{r}
library(pheatmap)
library(dplyr)
library(tibble)
library(ggimage)
library(RColorBrewer)
library(ggsci)
# library(plyr)
library(stringr)
library(tidyr)
library(reshape2)

my_col_bench<- pal_d3(palette = "category20", alpha = 1)(14)

mytemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(colour = "black"),axis.text.y =element_text(colour = "black"),
              axis.title.y=element_text(colour = "black"))

widetemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(angle = 30,size = 12,hjust = 1,colour = "black"),axis.text.y =element_text(size = 12,colour = "black"),
                axis.title.y=element_text(size=12,colour = "black"),legend.text=element_text(size=12))

rect_temp<-theme_bw()+theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.minor = element_blank(), panel.grid.major =element_blank(),axis.text.y =element_text(colour = "black"), axis.title.y=element_text(colour = "black"))

basecol<-function(n){
  colall<-c('#d7191c','#31a354','#756bb1','#0571b0','#d95f0e','#bdbdbd')
  return(colall[c(1:n)])
}
source("../plot_scmmib_table.r")
```



# 1.3 Unpair diagonal RNA+ATAC accuracy

```{r}
# load diagonal metric summary
diagonal_rna_atac_bmmc_p10_acc<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/accuracy/diagonal_scRNA+scATAC_accuracy_BMMC_p10_unpaired_metrics_summary.csv",sep=',',header = T,row.names = 1)
# 

diagonal_rna_atac_share_raw_acc<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/accuracy/diagonal_scRNA+scATAC_accuracy_SHARE_RawData_unpaired_metrics_summary.csv",sep=',',header = T,row.names = 1)

diagonal_rna_atac_hspc_p10_acc<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/accuracy/diagonal_scRNA+scATAC_accuracy_HSPC_p10_unpaired_metrics_summary.csv",sep=',',header = T,row.names = 1)

diagonal_rna_atac_pbmc_acc<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/accuracy/diagonal_scRNA+scATAC_accuracy_10xPBMC_RawData_unpaired_metrics_summary.csv",sep=',',header = T,row.names = 1)

diagonal_rna_atac_brain_acc<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/accuracy/diagonal_scRNA+scATAC_accuracy_10xMouseBrain_2p5_unpaired_metrics_summary.csv",sep=',',header = T,row.names = 1)

# prepare built-in functions

get_score<-function(x){
  return((x-min(x,na.rm = T))/(max(x,na.rm = T)-min(x,na.rm = T)))
}


map_alogr_name<-function(raw_name){
  return(plyr::mapvalues(raw_name, from = c("bindSC","scglue","LIGER_INMF","LIGER_OINMF","LIGER_UINMF","MaxFuse","MultiMAP","pamona","SCALEX","SeuratV3_CCA","SeuratV4_RPCA","SIMBA","unionCom","uniPort"),
                         to=c("bindSC","GLUE","LIGER iNMF","LIGER online iNMF","LIGER UINMF","MaxFuse","MultiMAP","Pamona","SCALEX","Seurat v3 CCA","Seurat v4 RPCA","SIMBA","unionCom","uniPort")))
}

select_metrics1 <- c("ARI","ARI.l1","AMI","AMI.l1","graph_cLISI","graph_cLISI.l1","isolated_labels_ASW","isolated_labels_ASW.l1")
select_col_names<- c(paste0(select_metrics1,".RNA"),paste0(select_metrics1,".ATAC"),"nearest_cell_barcode","nearest_cell_celltype.l1","nearest_cell_celltype","FOSCTTM","method","Output","nCell")

select_metrics2<-c("ARI","ARI level 1","AMI","AMI level 1","graph cLISI","graph cLISI level 1","isolated labels ASW","isolated labels ASW level 1")
select_col_names2<-c(paste0(select_metrics2,".RNA"),paste0(select_metrics2,".ATAC"),"Cell match","Cell type level 1 match","Cell type match","FOSCTTM")


map_metrics_name<-function(raw_name){
  metric1<- c(paste0(select_metrics1,".RNA"),paste0(select_metrics1,".ATAC"),"nearest_cell_barcode","nearest_cell_celltype.l1","nearest_cell_celltype","FOSCTTM")
  metric2<-  select_col_names2
  return(plyr::mapvalues(raw_name, from = metric1, to=metric2))
}
# 
# map_metrics_name2<-function(raw_name){
#   metric1<-c("Batch_ASW_batch","Batch_ASW_site","graph_connectivity","graph_connectivity.l1","graph_iLISI","ARI","ARI.l1","AMI","AMI.l1","graph_cLISI","graph_cLISI.l1","isolated_labels_ASW","isolated_labels_ASW.l1")
#   metric2<-c("Batch ASW batch","Batch ASW site","graph connectivity","graph connectivity level 1","graph iLISI","ARI","ARI level 1","AMI","AMI level 1","graph cLISI","graph cLISI level 1","isolated labels ASW","isolated labels ASW level 1")
#   metric_in<- c(paste(metric1,"RNA",sep="_"),paste(metric1,"ADT",sep="_"),paste(metric1,"Both",sep="_"))
#   metric_out<- c(paste(metric2,"RNA",sep=" "),paste(metric2,"ADT",sep=" "),paste(metric2,"Both",sep=" "))
#   return(plyr::mapvalues(raw_name, from =metric_in , to=metric_out))
# }
# 
map_dataset_name<-function(raw_name){
  return(plyr::mapvalues(raw_name,from = c("BMMC_p10_single_embed","BMMC_p10_cross_embed","SHARE_single_embed","SHARE_cross_embed","hspc_p10_cross_embed","pbmc_cross_embed","brain_cross_embed","single_embed_score","cross_embed_score","final_score"),to =c("BMMC Multiome p10 Embedding Acc","BMMC Multiome p10 Cell Alignment Acc","SHARE-seq skin Embedding Acc","SHARE-seq skin Cell Alignment Acc","HSPC Multiome p10 Cell Alignment Acc","10X PBMC Multiome Cell Alignment Acc","10X mouse brian Cell Alignment Acc","Embedding accuracy score","Cell alignment accuracy score","Overall score") ))
}


gpu_tools <- c("unionCom","cobolt","DCCA","GLUE","scDEC","scMM","scMVAE","totalVI","Multigrate","SCALEX","sciPENN","scMDC","scMVP","uniPort","scVAEIT","DeepMAPS","MultiVI","scMoMaT","SpatialGlue","MIDAS")
cpu_tools <- c("LIGER iNMF","Seurat v3 CCA","Seurat v4 RPCA","CiteFuse","MOFA+","scAI","LIGER online iNMF","Seurat v4 WNN","MultiMAP","bindSC","LIGER UINMF","Pamona","MEFISTO","MaxFuse","SIMBA","Seurat v5 bridge","StabMap")



# refine algorithm names.
diagonal_rna_atac_bmmc_p10_acc$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_bmmc_p10_acc$method))
diagonal_rna_atac_share_raw_acc$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_share_raw_acc$method))
diagonal_rna_atac_hspc_p10_acc$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_hspc_p10_acc$method))
diagonal_rna_atac_pbmc_acc$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_pbmc_acc$method))
diagonal_rna_atac_brain_acc$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_brain_acc$method))


# 分数据集计算均值
diagonal_rna_atac_bmmc_p10_acc_avg <- diagonal_rna_atac_bmmc_p10_acc %>% dplyr::group_by(method) %>% dplyr::summarise(ARI.RNA=median(ARI.RNA),AMI.RNA=median(AMI.RNA),graph_cLISI.RNA=median(graph_cLISI.RNA),isolated_labels_ASW.RNA=median(isolated_labels_ASW.RNA),ARI.ATAC=median(ARI.ATAC),AMI.ATAC=median(AMI.ATAC),graph_cLISI.ATAC=median(graph_cLISI.ATAC),isolated_labels_ASW.ATAC=median(isolated_labels_ASW.ATAC),ARI.l1.RNA=median(ARI.l1.RNA),AMI.l1.RNA=median(AMI.l1.RNA),graph_cLISI.l1.RNA=median(graph_cLISI.l1.RNA),isolated_labels_ASW.l1.RNA=median(isolated_labels_ASW.l1.RNA),ARI.l1.ATAC=median(ARI.l1.ATAC),AMI.l1.ATAC=median(AMI.l1.ATAC),graph_cLISI.l1.ATAC=median(graph_cLISI.l1.ATAC),isolated_labels_ASW.l1.ATAC=median(isolated_labels_ASW.l1.ATAC),FOSCTTM_neg=median(1-FOSCTTM),nearest_cell_celltype=median(nearest_cell_celltype),nearest_cell_celltype.l1=median(nearest_cell_celltype.l1),nearest_cell_barcode=median(nearest_cell_barcode))


diagonal_rna_atac_share_raw_acc_avg <- diagonal_rna_atac_share_raw_acc  %>% dplyr::group_by(method) %>% dplyr::summarise(ARI.RNA=median(ARI.RNA),AMI.RNA=median(AMI.RNA),graph_cLISI.RNA=median(graph_cLISI.RNA),ARI.ATAC=median(ARI.ATAC),AMI.ATAC=median(AMI.ATAC),graph_cLISI.ATAC=median(graph_cLISI.ATAC),FOSCTTM_neg=median(1-FOSCTTM),nearest_cell_celltype=median(nearest_cell_celltype),nearest_cell_barcode=median(nearest_cell_barcode))

diagonal_rna_atac_hspc_p10_acc_avg <-diagonal_rna_atac_hspc_p10_acc  %>% dplyr::group_by(method) %>% dplyr::summarise(FOSCTTM_neg=median(1-FOSCTTM),nearest_cell_barcode=median(nearest_cell_barcode))

diagonal_rna_atac_pbmc_acc_avg <-diagonal_rna_atac_pbmc_acc  %>% dplyr::group_by(method) %>% dplyr::summarise(FOSCTTM_neg=median(1-FOSCTTM),nearest_cell_barcode=median(nearest_cell_barcode))

diagonal_rna_atac_brain_acc_avg <-diagonal_rna_atac_brain_acc  %>% dplyr::group_by(method) %>% dplyr::summarise(FOSCTTM_neg=median(1-FOSCTTM),nearest_cell_barcode=median(nearest_cell_barcode))


## BMMC p10

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(ARI.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(ARI.RNA) %>%
  arrange(ARI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_ARI.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(AMI.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(AMI.RNA) %>% 
  arrange(AMI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_AMI.RNA_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(graph_cLISI.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(graph_cLISI.RNA) %>% 
  arrange(graph_cLISI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_graph_cLISI.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(isolated_labels_ASW.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(isolated_labels_ASW.RNA) %>% 
  arrange(isolated_labels_ASW.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=isolated_labels_ASW.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Isolated Labels ASW.RNA")+ggtitle("BMMC p10") + theme(plot.margin=unit(c(0,1,0,0),'lines'))
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_isolated_labels_ASW.RNA_boxplot.pdf",height=5,width=3)

# BMMC level 1 metrics.

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(graph_cLISI.l1.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(graph_cLISI.l1.RNA) %>% 
  arrange(graph_cLISI.l1.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.l1.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI level 1.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_graph_cLISI.l1.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(isolated_labels_ASW.l1.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(isolated_labels_ASW.l1.RNA) %>% 
  arrange(isolated_labels_ASW.l1.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=isolated_labels_ASW.l1.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Isolated Labels ASW level 1.RNA")+ggtitle("BMMC p10") + theme(plot.margin=unit(c(0,3,0,0),'lines'))
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_isolated_labels_ASW.l1.RNA_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(ARI.l1.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(ARI.l1.RNA) %>%
  arrange(ARI.l1.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.l1.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI level 1.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_ARI.l1.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(AMI.l1.RNA)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(AMI.l1.RNA) %>% 
  arrange(AMI.l1.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.l1.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI level 1.RNA")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_AMI.l1.RNA_boxplot.pdf",height=5,width=3)




p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(ARI.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(ARI.ATAC) %>%
  arrange(ARI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_ARI.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(AMI.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(AMI.ATAC) %>% 
  arrange(AMI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_AMI.ATAC_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(graph_cLISI.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(graph_cLISI.ATAC) %>% 
  arrange(graph_cLISI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_graph_cLISI.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(isolated_labels_ASW.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(isolated_labels_ASW.ATAC) %>% 
  arrange(isolated_labels_ASW.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=isolated_labels_ASW.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Isolated Labels ASW.ATAC")+ggtitle("BMMC p10") + theme(plot.margin=unit(c(0,1,0,0),'lines'))
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_isolated_labels_ASW.ATAC_boxplot.pdf",height=5,width=3)

# BMMC level 1 metrics.

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(graph_cLISI.l1.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(graph_cLISI.l1.ATAC) %>% 
  arrange(graph_cLISI.l1.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.l1.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI level 1.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_graph_cLISI.l1.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(isolated_labels_ASW.l1.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(isolated_labels_ASW.l1.ATAC) %>% 
  arrange(isolated_labels_ASW.l1.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=isolated_labels_ASW.l1.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Isolated Labels ASW level 1.ATAC")+ggtitle("BMMC p10") + theme(plot.margin=unit(c(0,3,0,0),'lines'))
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_isolated_labels_ASW.l1.ATAC_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(ARI.l1.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(ARI.l1.ATAC) %>%
  arrange(ARI.l1.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.l1.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI level 1.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_ARI.l1.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(AMI.l1.ATAC)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(AMI.l1.ATAC) %>% 
  arrange(AMI.l1.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.l1.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI level 1.ATAC")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_AMI.l1.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(nearest_cell_barcode)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(nearest_cell_barcode) %>%
  arrange(nearest_cell_barcode)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_barcode))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell  match")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_nearest_cell_barcode_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(nearest_cell_celltype)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(nearest_cell_celltype) %>%
  arrange(nearest_cell_celltype)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_celltype))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell type match")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_nearest_cell_celltype_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(nearest_cell_celltype.l1)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(nearest_cell_celltype.l1) %>%
  arrange(nearest_cell_celltype.l1)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_celltype.l1))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell type level 1 match")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_nearest_cell_celltype.l1_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_bmmc_p10_acc %>% drop_na(FOSCTTM)
label_median <- diagonal_rna_atac_bmmc_p10_acc_avg %>% drop_na(FOSCTTM_neg) %>%
  arrange(FOSCTTM_neg)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=FOSCTTM))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("FOSCTTM")+ggtitle("BMMC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_BMMC_p10_FOSCTTM_boxplot.pdf",height=5,width=3)

# Then SHARE-seq metrics
p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(ARI.RNA)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(ARI.RNA) %>%
  arrange(ARI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI.RNA")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_ARI.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(AMI.RNA)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(AMI.RNA) %>% 
  arrange(AMI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI.RNA")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_AMI.RNA_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(graph_cLISI.RNA)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(graph_cLISI.RNA) %>%
  arrange(graph_cLISI.RNA)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.RNA))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI.RNA")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_graph_cLISI.RNA_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(ARI.ATAC)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(ARI.ATAC) %>%
  arrange(ARI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=ARI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("ARI.ATAC")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_ARI.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(AMI.ATAC)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(AMI.ATAC) %>% 
  arrange(AMI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=AMI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("AMI.ATAC")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_AMI.ATAC_boxplot.pdf",height=5,width=3)

p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(graph_cLISI.ATAC)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(graph_cLISI.ATAC) %>%
  arrange(graph_cLISI.ATAC)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=graph_cLISI.ATAC))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Graph cLISI.ATAC")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_graph_cLISI.ATAC_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(nearest_cell_barcode)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(nearest_cell_barcode) %>%
  arrange(nearest_cell_barcode)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_barcode))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell match")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_nearest_cell_barcode_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(nearest_cell_celltype)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(nearest_cell_celltype) %>%
  arrange(nearest_cell_celltype)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_celltype))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell type match")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_nearest_cell_celltype_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_share_raw_acc %>% drop_na(FOSCTTM)
label_median <- diagonal_rna_atac_share_raw_acc_avg %>% drop_na(FOSCTTM_neg) %>%
  arrange(FOSCTTM_neg)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=FOSCTTM))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("FOSCTTM")+ggtitle("SHARE-seq skin")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_SHARE_FOSCTTM_boxplot.pdf",height=5,width=3)


# other datasets
p_tab<-diagonal_rna_atac_hspc_p10_acc %>% drop_na(nearest_cell_barcode)
label_median <- diagonal_rna_atac_hspc_p10_acc_avg %>% drop_na(nearest_cell_barcode) %>%
  arrange(nearest_cell_barcode)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_barcode))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell match")+ggtitle("HSPC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_HSPC_p10_nearest_cell_barcode_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_hspc_p10_acc %>% drop_na(FOSCTTM)
label_median <- diagonal_rna_atac_hspc_p10_acc_avg %>% drop_na(FOSCTTM_neg) %>%
  arrange(FOSCTTM_neg)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=FOSCTTM))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("FOSCTTM")+ggtitle("HSPC p10")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_HSPC_p10_FOSCTTM_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_pbmc_acc %>% drop_na(nearest_cell_barcode)
label_median <- diagonal_rna_atac_pbmc_acc_avg %>% drop_na(nearest_cell_barcode) %>%
  arrange(nearest_cell_barcode)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_barcode))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell match")+ggtitle("10X PBMC")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_10XPBMC_nearest_cell_barcode_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_pbmc_acc %>% drop_na(FOSCTTM)
label_median <- diagonal_rna_atac_pbmc_acc_avg %>% drop_na(FOSCTTM_neg) %>%
  arrange(FOSCTTM_neg)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=FOSCTTM))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("FOSCTTM")+ggtitle("10X PBMC")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_10XPBMC_FOSCTTM_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_brain_acc %>% drop_na(nearest_cell_barcode)
label_median <- diagonal_rna_atac_brain_acc_avg %>% drop_na(nearest_cell_barcode) %>%
  arrange(nearest_cell_barcode)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=nearest_cell_barcode))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("Cell match")+ggtitle("10X mouse brain")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_10X_mouse_brain_nearest_cell_barcode_boxplot.pdf",height=5,width=3)


p_tab<-diagonal_rna_atac_brain_acc %>% drop_na(FOSCTTM)
label_median <- diagonal_rna_atac_brain_acc_avg %>% drop_na(FOSCTTM_neg) %>%
  arrange(FOSCTTM_neg)
p_tab$method<-factor(p_tab$method,levels = label_median$method)
p<-ggplot(p_tab,aes(x=method,y=FOSCTTM))+geom_boxplot(width=0.7)+coord_flip()+rect_temp+xlab(NULL)+ylab("FOSCTTM")+ggtitle("10X mouse brain")
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_10X_mouse_brain_FOSCTTM_boxplot.pdf",height=5,width=3)

# metrics cor (deprecated)

merge_metric_mat<-function(metric_mats, prefixs, share_algor){
  out_tmp <- NA
  for (i in c(1:length(prefixs))){
    mat <- subset(metric_mats[[i]],method %in% share_algor)[,-1]
    colnames(mat)<-paste(colnames(mat),sep="_",prefixs[i])
    if (sum(is.na(out_tmp))==1){
      out_tmp<-mat
    }else{
      print(prefixs[i])
      print(nrow(mat))
      out_tmp<-cbind(out_tmp, mat)
    }
  }
  return(out_tmp)
}

# Evaluate the metrics score in all data
BMMC_p10_single_embed1<-data.frame(
  RNA_l2=rowMeans(apply(diagonal_rna_atac_bmmc_p10_acc_avg[,c(2:5)],2, get_score),na.rm = T),
  RNA_l1=rowMeans(apply(diagonal_rna_atac_bmmc_p10_acc_avg[,c(6:9)],2, get_score),na.rm = T),
  ATAC_l2=rowMeans(apply(diagonal_rna_atac_bmmc_p10_acc_avg[,c(10:13)],2, get_score),na.rm = T),
  ATAC_l1=rowMeans(apply(diagonal_rna_atac_bmmc_p10_acc_avg[,c(14:17)],2, get_score),na.rm = T),
  algor=diagonal_rna_atac_bmmc_p10_acc_avg$method
)
BMMC_p10_single_embed2<-data.frame(
  BMMC_p10_single_embed=rowMeans(BMMC_p10_single_embed1[,c(1:4)]),
  algor=BMMC_p10_single_embed1$algor
)

BMMC_p10_cross_embed<-data.frame(
  BMMC_p10_cross_embed=rowMeans(apply(diagonal_rna_atac_bmmc_p10_acc_avg[,c(18,21)],2, get_score),na.rm=T),
  algor=diagonal_rna_atac_bmmc_p10_acc_avg$method
)

SHARE_single_embed1<-data.frame(
  RNA_embed=rowMeans(apply(diagonal_rna_atac_share_raw_acc_avg[,c(2:5)],2, get_score),na.rm = T),
  ATAC_embed=rowMeans(apply(diagonal_rna_atac_share_raw_acc_avg[,c(5:7)],2, get_score),na.rm = T),
  algor=diagonal_rna_atac_share_raw_acc_avg$method
)

SHARE_single_embed2<-data.frame(
  SHARE_single_embed=rowMeans(SHARE_single_embed1[,c(1:2)]),
  algor=SHARE_single_embed1$algor
)

SHARE_cross_embed<-data.frame(
  SHARE_cross_embed=rowMeans(apply(diagonal_rna_atac_share_raw_acc_avg[,c(8:10)],2, get_score),na.rm=T),
  algor=diagonal_rna_atac_share_raw_acc_avg$method
)


HSPC_p10_cross_embed<-data.frame(
  hspc_p10_cross_embed=rowMeans(apply(diagonal_rna_atac_hspc_p10_acc_avg[,c(2:3)],2, get_score),na.rm=T),
  algor=diagonal_rna_atac_hspc_p10_acc_avg$method
)
  
PBMC_cross_embed<-data.frame(
  pbmc_cross_embed=rowMeans(apply(diagonal_rna_atac_pbmc_acc_avg[,c(2:3)],2, get_score),na.rm=T),
  algor=diagonal_rna_atac_pbmc_acc_avg$method
)

Brain_cross_embed<-data.frame(
  brain_cross_embed=rowMeans(apply(diagonal_rna_atac_brain_acc_avg[,c(2:3)],2, get_score),na.rm=T),
  algor=diagonal_rna_atac_brain_acc_avg$method
)


multi_merge<-function(x,y,id="algor"){
  merge(x,y,by=id,all=T)
}

#
diagonal_rna_atac_metric_score_summary<-Reduce(multi_merge,list(BMMC_p10_single_embed2, BMMC_p10_cross_embed, SHARE_single_embed2, SHARE_cross_embed, HSPC_p10_cross_embed, PBMC_cross_embed, Brain_cross_embed))

colnames(diagonal_rna_atac_metric_score_summary)<-map_dataset_name(colnames(diagonal_rna_atac_metric_score_summary))

# score_summary_cor<-cor(na.omit(diagonal_rna_atac_metric_score_summary[,-1]))
# 
# pheatmap(score_summary_cor,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_metric_summary_cor_heatmap.pdf",cluster_rows = T,cluster_cols = T,show_rownames = T,show_colnames = T, display_numbers = T,number_format = "%.2f",width=8,height = 6)


# plot summary heatmap
diagonal_rna_atac_metric_score_summary$single_embed_score<-rowMeans(diagonal_rna_atac_metric_score_summary[,c(2,4)],na.rm = T)
diagonal_rna_atac_metric_score_summary$cross_embed_score<-rowMeans(diagonal_rna_atac_metric_score_summary[,c(3,5:8)],na.rm = T)

# diagonal_rna_atac_metric_score_summary$final_score<- 
#   0.5*diagonal_rna_atac_metric_score_summary$single_embed_score +
#   0.5*diagonal_rna_atac_metric_score_summary$cross_embed_score

p_tab <- diagonal_rna_atac_metric_score_summary %>% arrange(by=-(single_embed_score+cross_embed_score) )
rownames(p_tab)<-p_tab[,1]
p_tab<-p_tab[,c(2,4,3,5:10)]
colnames(p_tab)<- map_dataset_name(colnames(p_tab))

ann_col<-data.frame(row.names=colnames(p_tab),type=c(rep("Embedding accuracy",2),rep("Cell alignment accuracy",5),rep("Ranking",2)))
pheatmap(p_tab,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_metric_summary_score_heatmap.pdf",cluster_rows = F,cluster_cols = F,show_rownames = T,show_colnames = T, display_numbers = T,annotation_col = ann_col,number_format = "%.2f",width=8,height = 6)



# plot summary table
p_tab<-diagonal_rna_atac_metric_score_summary[,c(1,2,4,3,5:10)]
colnames(p_tab)[1]<- "method"
p_tab_rank <- p_tab %>% arrange(desc(single_embed_score+cross_embed_score)) %>% mutate(Rank=min_rank(desc(rank(single_embed_score)+rank(cross_embed_score)))) %>% select(Rank,everything())

colnames(p_tab_rank)<- map_dataset_name(colnames(p_tab_rank))
diagonal_acc_row_info <- data.frame(id = p_tab_rank$method)
diagonal_acc_column_info <- data.frame(id = colnames(p_tab_rank),
                          group = c("Text","Text",
                                    rep("Embedding accuracy", 2),
                                    rep("Cell alignment accuracy", 5), 
                                    "Embedding accuracy",
                                    "Cell alignment accuracy"), 
                          geom = c(rep("text",2),
                                   rep("circle",7),
                                   rep("bar",2)),
                          width = c(1.5,6.5,rep(2,9)),
                          overlay = F)
diagonal_acc_palettes <- list(   "Text" = "black",
                    "Embedding accuracy" = "Blues",
                   "Cell alignment accuracy" = "Greens"
                   )
p<-plot_scmmib_summary(data = p_tab_rank,
                       row_info = diagonal_acc_row_info,
                       column_info =diagonal_acc_column_info,
                       palettes = diagonal_acc_palettes,
                       rank = TRUE,
                       rect_normalize = T
                       )
# ggsave(p,file="../stage2_figs/metric_summary/soft_rank/diagonal_RNA_ATAC_accuracy.pdf",device=cairo_pdf,width = 210, height = 157, units = "mm")
ggsave(p,file="../stage2_figs/metric_summary/soft_rank/diagonal_RNA_ATAC_accuracy.pdf",width = 10, height =8)

# Calculate the SD and CV for diagonal scRNA and scATAC methods
# metric_cols<-colnames(diagonal_rna_atac_bmmc_p10_acc)[c(1,4:14)]
metric_cols<-setdiff(select_col_names,c("nCell","Output"))
calc_cv<-function(data,sel_cols=select_col_names){
  data2 <-data[,intersect(sel_cols,colnames(data))]
  out<-data2 %>% group_by(method) %>% summarise(across(.cols=everything(),.fns=cv)) %>% melt()
  return(out)
}
calc_sd<-function(data,sel_cols=select_col_names){
  data2 <-data[,intersect(sel_cols,colnames(data))]
  out<-data2 %>% group_by(method) %>% summarise(across(.cols=everything(),.fns=sd)) %>% melt()
  return(out)
}
cv <- function(x) 100*( sd(x)/mean(x))
cv_output<-c()
for (diagonal_data in list(diagonal_rna_atac_bmmc_p10_acc,diagonal_rna_atac_share_raw_acc,diagonal_rna_atac_hspc_p10_acc[,c(1,20:28)],diagonal_rna_atac_pbmc_acc,diagonal_rna_atac_brain_acc)){
  cv_output<-rbind(cv_output,calc_cv(diagonal_data,metric_cols))
}

cv_output<-subset(cv_output,abs(value)>0 | method %in% gpu_tools)
p<- ggplot(cv_output, aes(x=method,y=abs(value),col=method))+geom_boxplot(width=0.7)+geom_jitter(width=0.2,size=0.5)+mytemp+scale_color_manual(NULL,values=my_col_bench)  +ylab("Absolute coefficient of Variation")+xlab(NULL)+ylim(c(0,1))
ggplot2::ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_algorithm_cv_robust.pdf",width=7,height=4)


sd_output<-c()
for (diagonal_data in list(diagonal_rna_atac_bmmc_p10_acc,diagonal_rna_atac_share_raw_acc,diagonal_rna_atac_hspc_p10_acc[,c(1,20:28)],diagonal_rna_atac_pbmc_acc[,c(1,12:15)],diagonal_rna_atac_brain_acc[,c(1,10:15)])){
  sd_output<-rbind(sd_output,calc_sd(diagonal_data,metric_cols))
}

sd_output<-subset(sd_output,abs(value)>0 | method %in% gpu_tools)
p<- ggplot(sd_output, aes(x=method,y=abs(value),col=method))+geom_boxplot(width=0.7)+geom_jitter(width=0.2,size=0.5)+mytemp+scale_color_manual(NULL,values=my_col_bench)  +ylab("Standard deviation")+xlab(NULL)
ggplot2::ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_boxplot/diagonal_RNA+ATAC_algorithm_sd_robust.pdf",width=7,height=4)


html_out<- function(in_tab,sel_cols){
  colnames(in_tab)<- map_metrics_name(colnames(in_tab))
  in_tab[,sel_cols]<- round(in_tab[,sel_cols],3)
  return(in_tab)
}

write.table(html_out(diagonal_rna_atac_bmmc_p10_acc[,c(1:3,11:18,26:35,38,41)],4:23), file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_accuracy_BMMC_p10_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)


write.table(html_out(diagonal_rna_atac_share_raw_acc[,c(1:11,14)],4:12), file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_accuracy_SHARE_RawData_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)

write.table(html_out(diagonal_rna_atac_hspc_p10_acc[,c(1,27,28,20,21)],4:5), file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_accuracy_HSPC_p10_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)

write.table(html_out(diagonal_rna_atac_pbmc_acc[,c(1:3,12,13)],4:5), file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_accuracy_10xPBMC_RawData_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)

write.table(html_out(diagonal_rna_atac_brain_acc[,c(1,14,15,10,11)],4:5), file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_accuracy_10xMouseBrain_2p5_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)
```




# 2. robustness
```{r}
diagonal_rna_atac_bmmc_rob<-read.table("../stage2_res/SCMMIB_metrics_final/diagonal_scRNA+scATAC/robustness/diagonal_scRNA+scATAC_robustness_BMMC_p10_unpaired_metrics_summary.csv",sep=",",header=T,row.names = 1)

diagonal_rna_atac_bmmc_rob$RNA<-str_sub(diagonal_rna_atac_bmmc_rob$RNA,start=2)
diagonal_rna_atac_bmmc_rob$ATAC<-str_sub(diagonal_rna_atac_bmmc_rob$ATAC,start=2)
diagonal_rna_atac_bmmc_rob$method<-map_alogr_name(gsub("-louvain","",diagonal_rna_atac_bmmc_rob$method))

# colnames(diagonal_rna_atac_bmmc_rob)<-map_metrics_name(colnames(diagonal_rna_atac_bmmc_rob))
# 2.1 evaluate the robustness metrics across downsample gradients

p_tab<-subset(diagonal_rna_atac_bmmc_rob,RNA=="100" )[,intersect(colnames(diagonal_rna_atac_bmmc_rob),c(select_col_names,"RNA","ATAC"))]
p_tab2<-melt(p_tab[,c(1,4:25)],id.vars = c('method','RNA','ATAC'))
p_tab2$ATAC<-factor(p_tab2$ATAC,levels=c("10","25","50","75","100"))
p_tab2$variable<-map_metrics_name(p_tab2$variable)
p<-ggplot(p_tab2,aes(x=variable,y=value,fill=ATAC))+geom_boxplot(width=0.5)+scale_fill_manual("scATAC down level (%)",values=basecol(5))+widetemp+xlab(NULL)+ylab(NULL)

ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_down_ATAC_evaluation.pdf",width = 16,height=5)

p_tab2$variable<-as.factor(p_tab2$variable)
cor_tab1<- p_tab2 %>% dplyr::group_by(variable) %>% dplyr::summarise(cor_val=cor(value,as.numeric(ATAC),use = "complete.obs"),group="ATAC_down")

cor_tab1_avg1<- p_tab2 %>% dplyr::group_by(variable,ATAC) %>% dplyr::summarise(mean=mean(value,na.rm=T))
cor_tab1_avg2<- cor_tab1_avg1 %>% dplyr::group_by(variable)  %>% dplyr::summarise(cor_val=cor(mean,as.numeric(ATAC),use = "complete.obs"),group="ATAC_down")


p_tab<-subset(diagonal_rna_atac_bmmc_rob,ATAC=="100" )[,intersect(colnames(diagonal_rna_atac_bmmc_rob),c(select_col_names,"RNA","ATAC"))]
p_tab2<-melt(p_tab[,c(1,4:25)],id.vars = c('method','RNA','ATAC'))

p_tab2$RNA<-factor(p_tab2$RNA,levels=c("10","25","50","75","100"))
p_tab2$variable<-map_metrics_name(p_tab2$variable)
p_tab2$variable<-map_metrics_name(p_tab2$variable)

p<-ggplot(p_tab2,aes(x=variable,y=value,fill=RNA))+geom_boxplot(width=0.5)+scale_fill_manual("scRNA down level (%)",values=basecol(5))+widetemp+xlab(NULL)+ylab(NULL)
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_down_RNA_evaluation.pdf",width = 16,height=5)

cor_tab2<- p_tab2 %>% dplyr::group_by(variable) %>% dplyr::summarise(cor_val=cor(value,as.numeric(RNA),use = "complete.obs"),group="RNA_down")
cor_tab2_avg1<- p_tab2 %>% dplyr::group_by(variable,RNA) %>% dplyr::summarise(mean=mean(value,na.rm=T))
cor_tab2_avg2<- cor_tab2_avg1 %>% dplyr::group_by(variable)  %>% dplyr::summarise(cor_val=cor(mean,as.numeric(RNA),use = "complete.obs"),group="RNA_down")

p_tab<-subset(diagonal_rna_atac_bmmc_rob,ATAC==RNA)[,intersect(colnames(diagonal_rna_atac_bmmc_rob),c(select_col_names,"RNA","ATAC"))]
p_tab2<-melt(p_tab[,c(1,4:25)],id.vars = c('method','RNA','ATAC'))
p_tab2$RNA<-factor(p_tab2$RNA,levels=c("10","25","50","75","100"))
p_tab2$variable<-map_metrics_name(p_tab2$variable)

p<-ggplot(p_tab2,aes(x=variable,y=value,fill=RNA))+geom_boxplot(width=0.5)+scale_fill_manual("Both modality down level (%)",values=basecol(5))+widetemp+xlab(NULL)+ylab(NULL)
ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_down_both_evaluation.pdf",width = 16,height=5)

cor_tab3<- p_tab2 %>% dplyr::group_by(variable) %>% dplyr::summarise(cor_val=cor(value,as.numeric(RNA),use = "complete.obs"),group="Both_down")
cor_tab3_avg1<- p_tab2 %>% dplyr::group_by(variable,RNA) %>% dplyr::summarise(mean=mean(value,na.rm=T))
cor_tab3_avg2<- cor_tab3_avg1 %>% dplyr::group_by(variable)  %>% dplyr::summarise(cor_val=cor(mean,as.numeric(RNA),use = "complete.obs"),group="Both_down")


cor_tab<-rbind(cor_tab1,cor_tab2,cor_tab3)
cor_tab_avg<-rbind(cor_tab1_avg2,cor_tab2_avg2,cor_tab3_avg2)

p_tab<-dcast(cor_tab,group~variable,value.var="cor_val" )
rownames(p_tab)<-p_tab[,1]
p_tab<-p_tab[,-1]
colnames(p_tab)<-map_metrics_name(colnames(p_tab))
ann_col<-data.frame(row.names = colnames(p_tab),metric_type=c(rep("Embedding accuracy (RNA)",8),rep("Embedding accuracy (ATAC)",8),rep("Cell alignment accuracy",4)))

p_tab<-p_tab[c("Both_down","RNA_down","ATAC_down"),]
rownames(p_tab)<-c("Both modalities downsample","scRNA downsample","scATAC downsample")
pheatmap::pheatmap(p_tab,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_metric_correlation_all_heatmap.pdf",show_colnames = T,show_rownames = T,scale="none",annotation_col = ann_col,cluster_rows = F,cluster_cols = F,display_numbers = T, number_format = "%.2f",width = 11,height=3.5)


p_tab<-dcast(cor_tab_avg,group~variable,value.var="cor_val" )
rownames(p_tab)<-p_tab[,1]
p_tab<-p_tab[,-1]
colnames(p_tab)<-map_metrics_name(colnames(p_tab))
ann_col<-data.frame(row.names = colnames(p_tab),metric_type=c(rep("Embedding accuracy (RNA)",8),rep("Embedding accuracy (ATAC)",8),rep("Cell alignment accuracy",4)))
p_tab<-p_tab[c("Both_down","RNA_down","ATAC_down"),]
rownames(p_tab)<-c("Both modalities downsample","scRNA downsample","scATAC downsample")

pheatmap::pheatmap(p_tab,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_metric_correlation_mean_heatmap.pdf",show_colnames = T,show_rownames = T,scale="none",annotation_col = ann_col,cluster_rows = F,cluster_cols = F,display_numbers = T, number_format = "%.2f",width = 11,height=3.5)

# p<-ggplot(cor_tab,aes(x=variable,y=cor_val,col=group))+geom_point()+scale_color_manual(values=basecol(3))+widetemp+xlab(NULL)+ylab("Cor between down gradients and metrics")+ylim(c(-1,1))+geom_hline(yintercept = 0,mapping = NULL)
# ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_metric_correlation_all.pdf",width=10,height = 5)
# 
# p<-ggplot(cor_tab_avg,aes(x=variable,y=cor_val,col=group))+geom_point()+scale_color_manual(values=basecol(3))+widetemp+xlab(NULL)+ylab("Cor between down gradients and metrics")+ylim(c(-1,1))+geom_hline(yintercept = 0,mapping = NULL)
# ggsave(p,filename="../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_eval/diagonal_RNA+ATAC_robustness_metric_correlation_avg.pdf",width=10,height = 5)

# 2.2 Then summarise downsample 10% and down gradient auc sores with biological conservation metrics

# Down 10

get_score<-function(x){
  x2 = na.omit(x)
  return((x-min(x2))/(max(x2)-min(x2)))
}

down_cols<-select_col_names[1:21]
r_tab1<-subset(diagonal_rna_atac_bmmc_rob,RNA=="100" & ATAC=="10")[,intersect(colnames(diagonal_rna_atac_bmmc_rob),down_cols)]
r_tab2<-subset(diagonal_rna_atac_bmmc_rob,RNA=="10" & ATAC=="100")[,intersect(colnames(diagonal_rna_atac_bmmc_rob),down_cols)]
r_tab3<-subset(diagonal_rna_atac_bmmc_rob,RNA=="10" & ATAC=="10")[,intersect(colnames(diagonal_rna_atac_bmmc_rob),down_cols)]


colnames(r_tab1)[-1]<-paste0(map_metrics_name(colnames(r_tab1)[-1])," (ATAC down)")
colnames(r_tab2)[-1]<-paste0(map_metrics_name(colnames(r_tab2)[-1])," (RNA down)")
colnames(r_tab3)[-1]<-paste0(map_metrics_name(colnames(r_tab3)[-1])," (Both down)")

p_tab<-cbind(r_tab1[,-1],r_tab2[,-1],r_tab3[,-1])
p_tab2<-apply(p_tab,2,get_score)
rownames(p_tab)<-r_tab1[,1]
# colnames(p_tab)<-map_metrics_name(colnames(p_tab))
ann_col<-data.frame(row.names=colnames(p_tab),metric_grp=c(rep("ATAC down",20),rep("RNA down",20),rep("Both down",20)))
pheatmap(p_tab,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_downsample_10_full_heatmap.pdf",width=26,height=7,cluster_rows = F,cluster_cols = F,annotation_col = ann_col,display_numbers = T,number_format = "%.2f")

write.table(p_tab,file = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_downsample_10_full.txt",sep = "\t",row.names = T,col.names = T,quote=F)

# FOSCTTM lower is better.
r_tab1_tmp<-r_tab1
r_tab2_tmp<-r_tab2
r_tab3_tmp<-r_tab3
r_tab1_tmp[,18]<- 1-r_tab1_tmp[,18]
r_tab2_tmp[,18]<- 1-r_tab2_tmp[,18]
r_tab3_tmp[,18]<- 1-r_tab3_tmp[,18]

r_score_tab1<-data.frame(
                    ATAC_10=rowMeans(apply(r_tab1_tmp[,-1],2,get_score),na.rm = T),
                    RNA_10=rowMeans(apply(r_tab2_tmp[,-1],2,get_score),na.rm = T),
                    both_10=rowMeans(apply(r_tab3_tmp[,-1],2,get_score),na.rm = T)
                   )
rownames(r_score_tab1)<-r_tab1[,1]


# Downsample AUC score
calc_auc<-function(indata, increasing=T){
  if (!increasing){
    indata = rev(indata)
  }
  n_val=length(indata)
  # max_val=max(indata)
  max_val=indata[n_val]
  if (is.na(max_val)){
    return(NA)
  }
  if (max_val==0 && TRUE){
    return(NA)
  }else{
    x=indata/max_val
    x[x>1]<-1
    out = (x[1]+2*sum(x[2:(n_val-1)])+x[n_val])/(2*n_val-2)
    return(out)
  }
}

sel_tab<-subset(diagonal_rna_atac_bmmc_rob,RNA==100 )
sel_tab$ATAC<-factor(sel_tab$ATAC,levels=c("10","25","50","75","100"))
tmp_score1<-sel_tab %>% dplyr::group_by(method) %>% dplyr::summarise(ARI.RNA=calc_auc(ARI.RNA),
                                                      AMI.RNA=calc_auc(AMI.RNA),
                                                      graph_cLISI.RNA=calc_auc(graph_cLISI.RNA), 
                                                      isolated_labels_ASW.RNA=calc_auc(isolated_labels_ASW.RNA),
                                                      ARI.l1.RNA=calc_auc(ARI.l1.RNA),
                                                      AMI.l1.RNA=calc_auc(AMI.l1.RNA),
                                                      graph_cLISI.l1.RNA=calc_auc(graph_cLISI.l1.RNA), 
                                                      isolated_labels_ASW.l1.RNA=calc_auc(isolated_labels_ASW.l1.RNA),
                                                      ARI.ATAC=calc_auc(ARI.ATAC),
                                                      AMI.ATAC=calc_auc(AMI.ATAC),
                                                      graph_cLISI.ATAC=calc_auc(graph_cLISI.ATAC), 
                                                      isolated_labels_ASW.ATAC=calc_auc(isolated_labels_ASW.ATAC),
                                                      ARI.l1.ATAC=calc_auc(ARI.l1.ATAC),
                                                      AMI.l1.ATAC=calc_auc(AMI.l1.ATAC),
                                                      graph_cLISI.l1.ATAC=calc_auc(graph_cLISI.l1.ATAC), 
                                                      isolated_labels_ASW.l1.ATAC=calc_auc(isolated_labels_ASW.l1.ATAC),
                                                      FOSCTTM=calc_auc(1-FOSCTTM),
                                                      nearest_cell_barcode=calc_auc(nearest_cell_barcode),
                                                      nearest_cell_celltype=calc_auc(nearest_cell_celltype),
                                                      nearest_cell_celltype.l1=calc_auc(nearest_cell_celltype.l1)
                                                      )
tmp_score1<-data.frame(tmp_score1)
rownames(tmp_score1)<-tmp_score1[,1]
tmp_score1<-tmp_score1[,-1]
colnames(tmp_score1)<-paste0(map_metrics_name(colnames(tmp_score1))," (ATAC down)")


sel_tab<-subset(diagonal_rna_atac_bmmc_rob,ATAC==100 )
sel_tab$RNA<-factor(sel_tab$RNA,levels=c("10","25","50","75","100"))

tmp_score2<-sel_tab %>% group_by(method) %>% dplyr::summarise(ARI.RNA=calc_auc(ARI.RNA),
                                                      AMI.RNA=calc_auc(AMI.RNA),
                                                      graph_cLISI.RNA=calc_auc(graph_cLISI.RNA), 
                                                      isolated_labels_ASW.RNA=calc_auc(isolated_labels_ASW.RNA),
                                                      ARI.l1.RNA=calc_auc(ARI.l1.RNA),
                                                      AMI.l1.RNA=calc_auc(AMI.l1.RNA),
                                                      graph_cLISI.l1.RNA=calc_auc(graph_cLISI.l1.RNA), 
                                                      isolated_labels_ASW.l1.RNA=calc_auc(isolated_labels_ASW.l1.RNA),
                                                      ARI.ATAC=calc_auc(ARI.ATAC),
                                                      AMI.ATAC=calc_auc(AMI.ATAC),
                                                      graph_cLISI.ATAC=calc_auc(graph_cLISI.ATAC), 
                                                      isolated_labels_ASW.ATAC=calc_auc(isolated_labels_ASW.ATAC),
                                                      ARI.l1.ATAC=calc_auc(ARI.l1.ATAC),
                                                      AMI.l1.ATAC=calc_auc(AMI.l1.ATAC),
                                                      graph_cLISI.l1.ATAC=calc_auc(graph_cLISI.l1.ATAC), 
                                                      isolated_labels_ASW.l1.ATAC=calc_auc(isolated_labels_ASW.l1.ATAC),
                                                      FOSCTTM=calc_auc(1-FOSCTTM),
                                                      nearest_cell_barcode=calc_auc(nearest_cell_barcode),
                                                      nearest_cell_celltype=calc_auc(nearest_cell_celltype),
                                                      nearest_cell_celltype.l1=calc_auc(nearest_cell_celltype.l1)
                                                      )
tmp_score2<-data.frame(tmp_score2)
rownames(tmp_score2)<-tmp_score2[,1]
tmp_score2<-tmp_score2[,-1]
colnames(tmp_score2)<-paste0(map_metrics_name(colnames(tmp_score2))," (RNA down)")

sel_tab<-subset(diagonal_rna_atac_bmmc_rob,ATAC==RNA)
sel_tab$RNA<-factor(sel_tab$RNA,levels=c("10","25","50","75","100"))

tmp_score3<-sel_tab %>% group_by(method) %>% dplyr::summarise(ARI.RNA=calc_auc(ARI.RNA),
                                                      AMI.RNA=calc_auc(AMI.RNA),
                                                      graph_cLISI.RNA=calc_auc(graph_cLISI.RNA), 
                                                      isolated_labels_ASW.RNA=calc_auc(isolated_labels_ASW.RNA),
                                                      ARI.l1.RNA=calc_auc(ARI.l1.RNA),
                                                      AMI.l1.RNA=calc_auc(AMI.l1.RNA),
                                                      graph_cLISI.l1.RNA=calc_auc(graph_cLISI.l1.RNA), 
                                                      isolated_labels_ASW.l1.RNA=calc_auc(isolated_labels_ASW.l1.RNA),
                                                      ARI.ATAC=calc_auc(ARI.ATAC),
                                                      AMI.ATAC=calc_auc(AMI.ATAC),
                                                      graph_cLISI.ATAC=calc_auc(graph_cLISI.ATAC), 
                                                      isolated_labels_ASW.ATAC=calc_auc(isolated_labels_ASW.ATAC),
                                                      ARI.l1.ATAC=calc_auc(ARI.l1.ATAC),
                                                      AMI.l1.ATAC=calc_auc(AMI.l1.ATAC),
                                                      graph_cLISI.l1.ATAC=calc_auc(graph_cLISI.l1.ATAC), 
                                                      isolated_labels_ASW.l1.ATAC=calc_auc(isolated_labels_ASW.l1.ATAC),
                                                      FOSCTTM=calc_auc(1-FOSCTTM),
                                                      nearest_cell_barcode=calc_auc(nearest_cell_barcode),
                                                      nearest_cell_celltype=calc_auc(nearest_cell_celltype),
                                                      nearest_cell_celltype.l1=calc_auc(nearest_cell_celltype.l1)
                                                      )
tmp_score3<-data.frame(tmp_score3)
rownames(tmp_score3)<-tmp_score3[,1]
tmp_score3<-tmp_score3[,-1]
colnames(tmp_score3)<-paste0(map_metrics_name(colnames(tmp_score3))," (Both down)")

p_tab<-cbind(tmp_score1,tmp_score2,tmp_score3)
ann_col<-data.frame(row.names=colnames(p_tab),metric_grp=c(rep("ATAC down",20),rep("RNA down",20),rep("Both down",20)))

write.table(p_tab,file = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_downsample_auc_full.txt",sep = "\t",row.names = T,col.names = T,quote=F)
pheatmap(p_tab,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_downsample_auc_full_heatmap.pdf",annotation_col = ann_col,cluster_rows = F,cluster_cols = F,height=7,width=26,display_numbers = T,number_format = "%.2f")

# 计算最终得分，绘制汇总结果热图。
diagonal_score<-function(data){
  atac_embed_score=rowMeans(data[,1:8])
  rna_embed_score=rowMeans(data[,9:16])
  cross_embed_score=(data[,17]+mean(data[,18])+mean(data[,19:20]))/3 # same weight for foscttm, cell barcode match and cell type match
  return(0.25*atac_embed_score+0.25*rna_embed_score+0.5*rna_embed_score)  # 0.5 weight for single embedding and cross embedding
}


auc_score<-data.frame(ATAC_down_auc=diagonal_score(apply(tmp_score1,2,get_score)),
                      RNA_down_auc=diagonal_score(apply(tmp_score2,2,get_score)),
                      Both_down_auc=diagonal_score(apply(tmp_score3,2,get_score))
                      )
rownames(auc_score)<-rownames(tmp_score1)
auc_score<-auc_score[rownames(r_score_tab1),]
down_sample_final<-cbind(r_score_tab1,auc_score)
down_sample_final$down10_score<-rowMeans(r_score_tab1)
down_sample_final$down_auc<-rowMeans(auc_score)
# down_sample_final$final_score=0.5*rowMeans(r_score_tab1)+0.5*rowMeans(auc_score)
down_sample_final<-down_sample_final %>% dplyr::arrange(desc(rank(down10_score)+rank(down_auc)))

colnames(down_sample_final)<-c("ATAC 10%","RNA 10%","Both 10%","ATAC Down AUC","RNA Down AUC","Both Down AUC","Down 10% score","Down AUC score")

ann_col<-data.frame(row.names=colnames(down_sample_final),metric_group=c(rep("Metric score with 10% seq depth",3),rep("Downsample AUC",3),rep("Score summary",2)))
pheatmap(down_sample_final,filename = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_down_sample_final.pdf",width=8,height=5,annotation_col = ann_col,cluster_rows = F,cluster_cols = F,display_numbers = T,number_format = "%.2f")
write.table(down_sample_final,file = "../stage2_figs/metric_summary/diagonal_RNA+ATAC/metric_heatmap/diagonal_RNA+ATAC_downsample_final.txt",sep = "\t",row.names = T,col.names = T,quote=F)


# summary rank plot
p_tab<-down_sample_final
p_tab<-cbind(rownames(p_tab),p_tab)
colnames(p_tab)[1]<- "method"

p_tab_rank <- p_tab %>% mutate(Rank=min_rank(desc(rank(`Down 10% score`)+rank(`Down AUC score`)))) %>% arrange(Rank)  %>% select(Rank,everything())


diagonal_rob_row_info <- data.frame(id = p_tab_rank$method)
diagonal_rob_column_info <- data.frame(id = colnames(p_tab_rank),
                          group = c("Text","Text",
                                    rep("Metric score with 10% seq depth", 3),
                                    rep("Downsample AUC", 3), 
                                    "Metric score with 10% seq depth",
                                    "Downsample AUC"), 
                          geom = c(rep("text",2),
                                   rep("circle",6),
                                   rep("bar",2)),
                          width = c(1.5,8.5,rep(2,8)),
                          overlay = F)
diagonal_rob_palettes <- list(   "Text" = "black",
                    "Metric score with 10% seq depth" = "Blues",
                   "Downsample AUC" = "Greens",
                   "Overall score" = "Oranges"
                   )
p<-plot_scmmib_summary(data = p_tab_rank,
                       row_info = diagonal_rob_row_info,
                       column_info =diagonal_rob_column_info,
                       palettes = diagonal_rob_palettes,
                       rank = TRUE,
                       rect_normalize = T
                       )
# ggsave(p,file="../stage2_figs/metric_summary/soft_rank/diagonal_RNA_ATAC_robustness.pdf",device = cairo_pdf,width = 210, height = 157, units = "mm")
ggsave(p,file="../stage2_figs/metric_summary/soft_rank/diagonal_RNA_ATAC_robustness.pdf",width = 10, height = 8)

# Generate input files for html visualization.  
diagonal_rna_atac_bmmc_rob_html <- diagonal_rna_atac_bmmc_rob[,c(1:3,11:18,26:35,38,41,44,45)]
colnames(diagonal_rna_atac_bmmc_rob_html)<-map_metrics_name(colnames(diagonal_rna_atac_bmmc_rob_html))
diagonal_rna_atac_bmmc_rob_html[,c(4:23)]<-round(diagonal_rna_atac_bmmc_rob_html[,c(4:23)],3)
write.table(diagonal_rna_atac_bmmc_rob_html, file = "../stage2_res/SCMMIB_metrics_final/html_visualization_files/diagonal_scRNA+scATAC_robustness_BMMC_p10_metrics_summary.csv",sep=",",row.names = F,col.names = T,quote = F)
```

