```{r}
library(pheatmap)
library(dplyr)
library(tibble)
library(ggimage)
library(RColorBrewer)

my_col_bench<- pal_d3(palette = "category20", alpha = 1)(14)

mytemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(colour = "black"),axis.text.y =element_text(colour = "black"),
              axis.title.y=element_text(colour = "black"))

widetemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(angle = 30,size = 12,hjust = 1,colour = "black"),axis.text.y =element_text(size = 12,colour = "black"),
                axis.title.y=element_text(size=12,colour = "black"),legend.text=element_text(size=12))

rect_temp<-theme_bw()+theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.minor = element_blank(), panel.grid.major =element_blank(),axis.text.y =element_text(colour = "black"), axis.title.y=element_text(colour = "black"))

basecol<-function(n){
  colall<-c('#d7191c','#31a354','#756bb1','#0571b0','#d95f0e','#bdbdbd')
  return(colall[c(1:n)])
}
source("../plot_scmmib_table.r")
```

```{r}
spatial_lymph_a1_bio_cons<-read.csv("../stage2_res/SCMMIB_metrics_final/spatial_scRNA+ADT/accuracy/spatial_scRNA+ADT_accuracy_lymph_node_A1_paired_metrics_summary.csv",row.names = 1)
spatial_lymph_batch_rm<-read.csv("../stage2_res/SCMMIB_metrics_final/spatial_scRNA+ADT/accuracy/spatial_scRNA+ADT_accuracy_lymph_node_paired_metrics_summary.csv",row.names = 1)
spatial_spleen_batch_rm<-read.csv("../stage2_res/SCMMIB_metrics_final/spatial_scRNA+ADT/accuracy/spatial_scRNA+ADT_accuracy_spleen_paired_metrics_summary.csv",row.names = 1)
spatial_thymus_batch_rm<-read.csv("../stage2_res/SCMMIB_metrics_final/spatial_scRNA+ADT/accuracy/spatial_scRNA+ADT_accuracy_thymus_paired_metrics_summary.csv",row.names = 1)

# spatial_lymph_a1_bio_cons$method <-str_split(spatial_lymph_a1_bio_cons[,1],pattern = "-",simplify = T)[,1]
# spatial_lymph_batch_rm$method<-str_split(str_split(spatial_lymph_batch_rm[,1],pattern="/",simplify = T)[,12],pattern = "-",simplify = T)[,1]
# spatial_spleen_batch_rm$method<-str_split(str_split(spatial_spleen_batch_rm[,1],pattern="/",simplify = T)[,12],pattern = "-",simplify = T)[,1]
# spatial_thymus_batch_rm$method<-str_split(str_split(spatial_thymus_batch_rm[,1],pattern="/",simplify = T)[,12],pattern = "-",simplify = T)[,1]

# plot merged heatmap for spatial multiomics algorithms 
multi_merge<-function(x,y,id="method"){
  merge(x,y,by=id,all=T)
}
get_score<-function(x){
  x2 = na.omit(x)
  return((x-min(x2))/(max(x2)-min(x2)))
}
map_alogr_name<-function(raw_name){
  return(plyr::mapvalues(raw_name, from =c("harmony","mefisto","multimap","spglue","staligner"),
                         to=c("Harmony","MEFISTO","MultiMAP","SpatialGLUE","STAligner")))
}
map_metrics_name<-function(raw_name){
  return(plyr::mapvalues(raw_name, from = c("ARI_lymph","AMI_lymph","graph_cLISI_lymph","Batch_ASW_batch_lymph","graph_iLISI_lymph","Batch_ASW_batch_spleen","graph_iLISI_spleen","Batch_ASW_batch_thymus","graph_iLISI_thymus","bio_cons_score","batch_rm_score","final_score"),
                          to=c("ARI Lymph node","AMI Lymph node","graph cLISI Lymph node","Batch ASW Lymph node","graph iLISI Lymph node","Batch ASW Spleen","graph iLISI Spleen","Batch ASW Thymus","graph iLISI Thymus","Bio conservation score","Batch removal score","Overall score")))
}

tmp_tab1<-spatial_lymph_a1_bio_cons[,5:7]
colnames(tmp_tab1)<-paste0(colnames(tmp_tab1),"_lymph")
tmp_tab2<-spatial_lymph_batch_rm[,4:5]
colnames(tmp_tab2)<-paste0(colnames(tmp_tab2),"_lymph")
tmp_tab3<-spatial_spleen_batch_rm[,4:5]
colnames(tmp_tab3)<-paste0(colnames(tmp_tab3),"_spleen")
tmp_tab4<-spatial_thymus_batch_rm[,4:5]
colnames(tmp_tab4)<-paste0(colnames(tmp_tab4),"_thymus")

p_tab<-cbind(tmp_tab1,tmp_tab2,tmp_tab3,tmp_tab4)
p_tab$method<-spatial_spleen_batch_rm$method
p_tab2<- p_tab %>% dplyr::group_by(method) %>% dplyr::summarise(across(everything(), \(x) mean(x, na.rm = TRUE))) %>% as.data.frame()

rownames(p_tab2)<-p_tab2$method
p_tab2<-p_tab2[,-1]

score_tab = apply(p_tab2,2,get_score)

p_tab2$bio_cons_score<-rowMeans(score_tab[,1:3])
p_tab2$batch_rm_score<-rowMeans(score_tab[,4:9])
# p_tab2$final_score<-0.5*p_tab2$bio_cons_score + 0.5*p_tab2$batch_rm_score
# 
# p_tab2<- p_tab2 %>% dplyr::arrange(desc(final_score))
rownames(p_tab2)<- map_alogr_name(rownames(p_tab2))
colnames(p_tab2)<-map_metrics_name(colnames(p_tab2))
p_tab2<-p_tab2[c("SpatialGLUE","MEFISTO","MultiMAP","STAligner","Harmony"),]

ann_col<-data.frame(row.names = colnames(p_tab2),metric_type=c(rep("Bio Conservation",3),rep("Batch removal",6),rep("Ranking",2)),
                    dataset=c(rep("Lymph Node",5),rep("Spleen",2),rep("Thymus",2), rep(NA,2)))
ann_row<-data.frame(row.names = rownames(p_tab2),type=c(rep("Spatial CITE-seq integration methods",3),rep("Spatial batch correction methods",2)))


pheatmap(p_tab2,annotation_col = ann_col,annotation_row = ann_row,show_rownames = T,show_colnames = T,scale="none",cluster_rows = F,cluster_cols = F, display_numbers = T, number_format = "%.2f",
         filename = "../stage2_figs/metric_summary/spatial_RNA+ADT/spatial_RNA+ADT_metric_summary_heatmap.pdf",height = 4,width=10)
```

